### ISSUE TITLE
r4ids.cn multi function v1.51c firmware

### ISSUE THREAD

**Issue by soulpower11** [hansoljin/flashcard-archive#3]
I have the v1.51c firmware https://mega.nz/file/UskFkQBT#fGg5q96xsVwFfIoHK6nRrWyA-JAjdYegs3G24tbMnTc 
might be helpful for people who wants it

**Comment by hansoljin** [comment]
The multi-function part of this kernel is interesting for archival. I wonder if the kernel can be updated while keeping the multi-function part intact. 

I'll take a look at this. Until I figure out how I want to integrate this, this issue will stay open.

**Comment by soulpower11** [comment]
Ye, you can update the included wood r4 to the latest 1.64

**Comment by hansoljin** [comment]
The `readme.txt` didn't really mention anything regarding updating Wood to 1.64. However, it is as trivial as just renaming 1.64 to `WOODR4.NDS` and replacing the one in the SD with it (and replacing `__rpg` of course.)

What I also noticed is that this is a moonshell fork, and it's a weird one at that. It's based on Moonshell 2.00 beta 5, but there are remnants of Moonshell 1.7? I know it isn't latest Moonshell because the latest MS plays flac and this doesn't.

I want to see if that can be changed.
